### ISSUE TITLE
Drake Meme

### ISSUE THREAD

**Issue by mejdi14** [theapache64/gh-meme-maker#57]
**Input**

```json
{
  "template_id": "drake-meme",
  "drake_hates": "doing the work that may make you successful",
  "drake_loves": "imagining that you're already successful",
  "font_size": 80
}
```

**Template**

<img src="https://raw.githubusercontent.com/theapache64/gh-meme-maker/master/template_images/drake.jpg" height="250"/>

*Please wait, we've just started cooking your meme 👨‍🍳. Meantime, click the '[Actions](https://github.com/theapache64/gh-meme-maker/actions)' tab if you want to see the kitchen 🍳*

**Comment by mejdi14** [comment]
this is awesome <3

**Comment by theapache64** [comment]
Thanks @mejdi14
