### ISSUE TITLE
Fireman Burns Meme

### ISSUE THREAD

**Issue by ime01** [theapache64/gh-meme-maker#67]
**Input**

```json
{
  "template_id": "fireman-burns-meme",
  "lady_says": "Dagger is so Easy",
  "font_size": 30
}
```
**Template**

<img src="https://raw.githubusercontent.com/theapache64/gh-meme-maker/master/template_images/fireman_burns.jpg" height="250" alt="template"/>

Please wait, we've just started cooking your meme 👨‍🍳. *Click the '[Actions](https://github.com/theapache64/gh-meme-maker/actions)' tab to see the kitchen 🍳 *

**Comment by theapache64** [comment]
@ime01 Did you like it? :wink:

**Comment by ime01** [comment]
yes! pretty cool stuff you have created here, nice one indeed

**Comment by theapache64** [comment]
Thanks buddy 🙇‍♂️
